# Generated by Django 5.2.17 on 2026-10-05 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_app_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_apps', to=settings.AUTH_USER_MODEL, verbose_name='В избранном'),
        ),
    ]
