# Generated by Django 5.2.17 on 2026-10-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_app_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='rating_avg',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=2, verbose_name='Средняя оценка'),
        ),
        migrations.AddField(
            model_name='app',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Число оценок'),
        ),
    ]
